name: Python CI with SonarCloud

on:
  push:
    branches: [ main, feature/GitHub-Actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Obligatorio para SonarCloud

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        python -m unittest discover -s . -p "test_*.py"
        
    - name: Configurar SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.8
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Ejecutar análisis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=ekaitzg04_Analisis_de_trafico_grupo_2 \
          -Dsonar.organization=ekaitzg04 \
          -Dsonar.sources=. \
          -Dsonar.python.version=3.10