name: Python CI with SonarCloud

on:
  push:
    branches: [ main, feature/GitHub-Actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configurar Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar SonarScanner (Java 17)
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip -d $HOME
        echo "$HOME/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

    - name: Ejecutar análisis SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
      run: |
        sonar-scanner \
          -Dsonar.projectKey=ekaitzg04_Analisis_de_trafico_grupo_2 \
          -Dsonar.organization=ekaitzg04 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.java.jdkHome=$JAVA_HOME \
          -Dsonar.sources=.
