name: Python CI

on:
  push:
    branches: [ main, feature/GitHub-Actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
          SONAR_FORCE_AUTHENTICATION: "false"

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip -d $HOME
        echo "$HOME/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

    - name: Wait for SonarQube
      run: |
        for i in {1..20}; do
          if curl -s http://localhost:9000/api/system/status | grep -q "UP"; then
            echo "SonarQube is ready!"
            break
          fi
          echo "Waiting for SonarQube to start..."
          sleep 10
        done

    - name: Ejecutar análisis de SonarQube
      run: |
        sonar-scanner -X \
          -Dsonar.projectKey=my_project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=admin \
          -Dsonar.password=admin