name: Python CI

on:
  push:
    branches: [ main, feature/GitHub-Actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Instalar SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner-cli-4.8.0.2856-linux.zip -d $HOME
        echo "$HOME/sonar-scanner-cli-4.8.0.2856-linux/bin" >> $GITHUB_PATH
        sonar-scanner --version

    - name: Ejecutar análisis de SonarQube
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my_project \
          -Dsonar.sources=. \
